---
version: "3.8"

services:
  collector:
    build:
      context: ./collector
    container_name: collector
    command:
    - "--config=file:/etc/otelcol/config.yml"
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: '500M'
        reservations:
          cpus: '1.00'
          memory: '100M'
    volumes:
      - "./config/collector.yml:/etc/otelcol/config.yml:ro"
    expose:
      - 8000
    depends_on:
    - pyroscope
    - jenkins
  jenkins:
    image: jenkins/jenkins:2.401.2
    container_name: jenkins
    ports:
    - 8080:8080
    volumes:
      - jenkins-data:/var/jenkins_home
  pyroscope:
    image: pyroscope/pyroscope:0.37.2
    container_name: pyroscope
    restart: on-failure
    ports: 
      - 4040:4040
    volumes:
      - "pyrscope-data:/var/lib/pyroscope"
    command:
    - server
    
volumes:
  pyrscope-data:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: size=5000m
  prometheus-data:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: size=5000m
  grafana-data:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: size=1000m
  loki-data:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: size=5000m
  tempo-data:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: size=5000m
  jenkins-data:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: size=5000m