---
extensions:
  pyroscope:
    endpoint: http://pyroscope:4040
    profiles:
    - cpu
    - alloc_objects
    - alloc_space
    - inuse_objects
    - inuse_space    
    - goroutines
    - mutex_count
    - mutex_duration
    - block_count
    - block_duration
  health_check:
    endpoint: 127.0.0.1:9098
    path: /health/status
    check_collector_pipeline:
      enabled: true
      interval: "1m"
      exporter_failure_threshold: 5
  
  basicauth/jenkins:
    client_auth:
      username: admin
      password: 110a7d1fe11c16c3807e4e2c2ff71a36be

processors:
  batch:
    timeout: 1s

receivers:
  otlp:
    protocols:
      grpc:
  jaeger:
    protocols:
      grpc:
  prometheus/self:
    config:
      scrape_configs:
      - job_name: 'otelcol'
        scrape_interval: 1m
        static_configs:
        - targets: ['127.0.0.1:8888']
  jenkins:
    endpoint: http://jenkins:8080
    auth:
      authenticator: basicauth/jenkins

exporters:
  logging:
    verbosity: detailed
service:
  telemetry:
    logs:
      level: info
      encoding: json
      disable_stacktrace: false
    metrics:
      level: basic
      address: 127.0.0.1:8888
  extensions:
    - pyroscope
    - health_check
    - basicauth/jenkins
  pipelines:
    metrics:
      receivers  : [jenkins]
      processors : [batch]
      exporters  : [logging]
    traces:
      receivers  : [otlp, jaeger]
      processors : [batch]
      exporters  : [logging]
    logs:
      receivers  : [otlp]
      processors : [batch]
      exporters  : [logging]